language: python

os: linux

cache:
  pip: true

jobs:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8
    - python: 3.9
      after_success: coveralls


script:
  - pip install -U pip setuptools wheel poetry
  - make setup lint coverage

before_deploy:
  - pip install --upgrade pip
  - pip install poetry
  - poetry config http-basic.pypi __token__ $PYPI_PASSWORD
  - poetry build -f wheel

deploy:
  provider: script
  script: poetry publish
  cleanup: false
  on:
    tags: true
    python: 3.6
    repo: thorgate/pyasice

notifications:
    email: false
